<?php

return [
    'can-create-posts'                           => 1,
    'can-modify-own-posts'                       => 2,
    'can-modify-members-posts'                   => 3,
    'can-modify-admins-posts'                    => 4,
    'can-view-pending-member-joining-requests'   => 5,
    'can-comment-on-posts'                       => 6,
    'can-comment-on-comments'                    => 7,
    'can-like-comments'                          => 8,
    'can-like-posts'                             => 9,
    'can-mention-non-members'                    => 10,
    'can-mention-members'                        => 11,
    'can-attach-videos-to-own-post'              => 12,
    'can-attach-videos-to-own-comment'           => 13,
    'can-attach-images-to-own-post'              => 14,
    'can-attach-images-to-own-comment'           => 15,
    'can-remove-posts'                           => 16,
    'can-remove-comments'                        => 17,
    'can-mute-members'                           => 18,
    'can-kick-members'                           => 19,
    'can-ban-members'                            => 20,
    'can-temporarly-ban-members'                 => 21,
    // 'can-share-verified-links'                   => 14,
    // 'can-share-unverified-links'                 => 15,
];
